/**
 * Karuta (かるた) deck data — Hyakunin Isshu poem cards.
 *
 * Each entry pairs a `reading` card (the full poem, read aloud) with a
 * `match` card (the distinctive lower verse the player must grab). The
 * `match` line is the traditional torifuda text: the second half of the
 * waka, which is what appears on a real karuta card.
 */

export interface KarutaCard {
  /** Stable identity, e.g. "hi-01". */
  id: string;
  /** Poem number in the Hyakunin Isshu anthology (1–100). */
  number: number;
  /** Poet credited with the poem. */
  poet: string;
  /** Full poem, the reading card. */
  reading: string;
  /** Lower verse shown on the matching card. */
  match: string;
  /** Romanised reading of the lower verse, for learners. */
  romaji: string;
  /** Short English gloss of the poem's image. */
  meaning: string;
}

export const KARUTA_CARDS: KarutaCard[] = [
  {
    id: "hi-01",
    number: 1,
    poet: "Emperor Tenji",
    reading: "秋の田の かりほの庵の 苫をあらみ わが衣手は 露にぬれつつ",
    match: "わが衣手は 露にぬれつつ",
    romaji: "waga koromode wa tsuyu ni nuretsutsu",
    meaning: "My sleeves grow wet with dew at the autumn field hut.",
  },
  {
    id: "hi-02",
    number: 2,
    poet: "Empress Jitō",
    reading: "春過ぎて 夏来にけらし 白妙の 衣ほすてふ 天の香具山",
    match: "衣ほすてふ 天の香具山",
    romaji: "koromo hosu chō ama no Kaguyama",
    meaning: "Summer has come — white robes dry on the slopes of Kagu.",
  },
  {
    id: "hi-03",
    number: 3,
    poet: "Kakinomoto no Hitomaro",
    reading: "あしびきの 山鳥の尾の しだり尾の ながながし夜を ひとりかも寝む",
    match: "ながながし夜を ひとりかも寝む",
    romaji: "naganagashi yo o hitori kamo nemu",
    meaning: "Must I sleep alone through this long, long night?",
  },
  {
    id: "hi-04",
    number: 4,
    poet: "Yamabe no Akahito",
    reading: "田子の浦に うち出でて見れば 白妙の 富士の高嶺に 雪は降りつつ",
    match: "富士の高嶺に 雪は降りつつ",
    romaji: "Fuji no takane ni yuki wa furitsutsu",
    meaning: "Snow falls on the high peak of Fuji.",
  },
  {
    id: "hi-05",
    number: 5,
    poet: "Sarumaru no Taifu",
    reading: "奥山に 紅葉踏み分け 鳴く鹿の 声聞く時ぞ 秋は悲しき",
    match: "声聞く時ぞ 秋は悲しき",
    romaji: "koe kiku toki zo aki wa kanashiki",
    meaning: "Autumn is saddest when the deer calls in the deep hills.",
  },
  {
    id: "hi-06",
    number: 6,
    poet: "Ōtomo no Yakamochi",
    reading: "鵲の 渡せる橋に おく霜の 白きを見れば 夜ぞ更けにける",
    match: "白きを見れば 夜ぞ更けにける",
    romaji: "shiroki o mireba yo zo fukenikeru",
    meaning: "Seeing the white frost, I know the night has deepened.",
  },
  {
    id: "hi-07",
    number: 7,
    poet: "Abe no Nakamaro",
    reading: "天の原 ふりさけ見れば 春日なる 三笠の山に 出でし月かも",
    match: "三笠の山に 出でし月かも",
    romaji: "Mikasa no yama ni ideshi tsuki kamo",
    meaning: "Is this the same moon that rose over Mount Mikasa?",
  },
  {
    id: "hi-08",
    number: 8,
    poet: "Kisen Hōshi",
    reading: "わが庵は 都のたつみ しかぞ住む 世をうぢ山と 人はいふなり",
    match: "世をうぢ山と 人はいふなり",
    romaji: "yo o Ujiyama to hito wa iu nari",
    meaning: "People call my hermitage the mountain of sorrow.",
  },
  {
    id: "hi-09",
    number: 9,
    poet: "Ono no Komachi",
    reading: "花の色は 移りにけりな いたづらに わが身世にふる ながめせしまに",
    match: "わが身世にふる ながめせしまに",
    romaji: "waga mi yo ni furu nagame seshi ma ni",
    meaning: "The flower's colour fades while I brood on the long rains.",
  },
  {
    id: "hi-10",
    number: 10,
    poet: "Semimaru",
    reading: "これやこの 行くも帰るも 別れては 知るも知らぬも 逢坂の関",
    match: "知るも知らぬも 逢坂の関",
    romaji: "shiru mo shiranu mo Ōsaka no seki",
    meaning: "Strangers and friends alike pass the barrier of Ōsaka.",
  },
  {
    id: "hi-11",
    number: 11,
    poet: "Sangi Takamura",
    reading: "わたの原 八十島かけて 漕ぎ出でぬと 人には告げよ 海人の釣舟",
    match: "人には告げよ 海人の釣舟",
    romaji: "hito ni wa tsugeyo ama no tsuribune",
    meaning: "Tell them, O fishing boats, that I row out to the isles.",
  },
  {
    id: "hi-12",
    number: 12,
    poet: "Sōjō Henjō",
    reading: "天つ風 雲の通ひ路 吹き閉ぢよ をとめの姿 しばしとどめむ",
    match: "をとめの姿 しばしとどめむ",
    romaji: "otome no sugata shibashi todomen",
    meaning: "Wind of heaven, close the cloud path — hold the dancers here.",
  },
  {
    id: "hi-13",
    number: 13,
    poet: "Emperor Yōzei",
    reading: "筑波嶺の 峰より落つる みなの川 恋ぞつもりて 淵となりぬる",
    match: "恋ぞつもりて 淵となりぬる",
    romaji: "koi zo tsumorite fuchi to narinuru",
    meaning: "My longing has gathered into a deep pool.",
  },
  {
    id: "hi-14",
    number: 14,
    poet: "Minamoto no Tōru",
    reading: "陸奥の しのぶもぢずり 誰ゆゑに 乱れそめにし われならなくに",
    match: "乱れそめにし われならなくに",
    romaji: "midare somenishi ware naranaku ni",
    meaning: "Why has my heart, not I, begun to fall into disorder?",
  },
  {
    id: "hi-15",
    number: 15,
    poet: "Emperor Kōkō",
    reading: "君がため 春の野に出でて 若菜つむ わが衣手に 雪は降りつつ",
    match: "わが衣手に 雪は降りつつ",
    romaji: "waga koromode ni yuki wa furitsutsu",
    meaning: "Snow falls on my sleeves as I gather spring greens for you.",
  },
  {
    id: "hi-16",
    number: 16,
    poet: "Ariwara no Narihira",
    reading: "立ち別れ いなばの山の 峰に生ふる まつとし聞かば 今帰り来む",
    match: "まつとし聞かば 今帰り来む",
    romaji: "matsu to shi kikaba ima kaeri kon",
    meaning: "If you say you wait, I will return at once.",
  },
  {
    id: "hi-17",
    number: 17,
    poet: "Ariwara no Narihira",
    reading: "ちはやぶる 神代もきかず 龍田川 からくれなゐに 水くくるとは",
    match: "からくれなゐに 水くくるとは",
    romaji: "kara kurenai ni mizu kukuru to wa",
    meaning: "Even in the age of gods, no river was dyed such crimson.",
  },
  {
    id: "hi-18",
    number: 18,
    poet: "Fujiwara no Toshiyuki",
    reading: "住の江の 岸に寄る波 よるさへや 夢の通ひ路 人目よくらむ",
    match: "夢の通ひ路 人目よくらむ",
    romaji: "yume no kayoiji hitome yokuramu",
    meaning: "Even on the dream path, do you shun the eyes of others?",
  },
  {
    id: "hi-19",
    number: 19,
    poet: "Ise",
    reading: "難波潟 みじかき芦の ふしの間も 逢はでこの世を 過ぐしてよとや",
    match: "逢はでこの世を 過ぐしてよとや",
    romaji: "awade kono yo o sugushite yo to ya",
    meaning: "Would you have me pass this life without meeting you?",
  },
  {
    id: "hi-20",
    number: 20,
    poet: "Motoyoshi Shinnō",
    reading: "わびぬれば 今はた同じ 難波なる みをつくしても 逢はむとぞ思ふ",
    match: "みをつくしても 逢はむとぞ思ふ",
    romaji: "mi o tsukushite mo awan to zo omou",
    meaning: "Even at the cost of my life, I mean to meet you.",
  },
  {
    id: "hi-21",
    number: 21,
    poet: "Sosei Hōshi",
    reading: "今来むと いひしばかりに 長月の 有明の月を 待ち出でつるかな",
    match: "有明の月を 待ち出でつるかな",
    romaji: "ariake no tsuki o machi idetsuru kana",
    meaning: "Because you said you would come, I waited for the dawn moon.",
  },
  {
    id: "hi-22",
    number: 22,
    poet: "Fun'ya no Yasuhide",
    reading: "吹くからに 秋の草木の しをるれば むべ山風を あらしといふらむ",
    match: "むべ山風を あらしといふらむ",
    romaji: "ube yamakaze o arashi to iuramu",
    meaning: "No wonder the mountain wind is called a storm.",
  },
  {
    id: "hi-23",
    number: 23,
    poet: "Ōe no Chisato",
    reading: "月見れば ちぢにものこそ 悲しけれ わが身一つの 秋にはあらねど",
    match: "わが身一つの 秋にはあらねど",
    romaji: "waga mi hitotsu no aki ni wa aranedo",
    meaning:
      "Seeing the moon, a thousand things sadden me — and not mine alone.",
  },
  {
    id: "hi-24",
    number: 24,
    poet: "Kanke",
    reading: "このたびは 幣もとりあへず 手向山 紅葉の錦 神のまにまに",
    match: "紅葉の錦 神のまにまに",
    romaji: "momiji no nishiki kami no manimani",
    meaning: "I offer brocade of autumn leaves, as the gods will.",
  },
  {
    id: "hi-25",
    number: 25,
    poet: "Sanjō no Machi",
    reading: "名にし負はば 逢坂山の さねかづら 人に知られで くるよしもがな",
    match: "人に知られで くるよしもがな",
    romaji: "hito ni shirarede kuru yoshi mo gana",
    meaning: "If only I could come to you unseen.",
  },
  {
    id: "hi-26",
    number: 26,
    poet: "Fujiwara no Tadahira",
    reading: "小倉山峰の 紅葉の 心あらば 今ひとたびの みゆき待たなむ",
    match: "今ひとたびの みゆき待たなむ",
    romaji: "ima hitotabi no miyuki matanan",
    meaning:
      "Leaves of Ogura, if you have a heart, wait for one more royal visit.",
  },
  {
    id: "hi-27",
    number: 27,
    poet: "Fujiwara no Kanesuke",
    reading: "みかの原 わきて流るる 泉川 いつ見きとてか 恋しかるらむ",
    match: "いつ見きとてか 恋しかるらむ",
    romaji: "itsu miki tote ka koishikaruramu",
    meaning: "When did I ever see her, that I should long so?",
  },
  {
    id: "hi-28",
    number: 28,
    poet: "Minamoto no Muneyuki",
    reading: "山里は 冬ぞさびしさまさりける 人目も草も かれぬと思へば",
    match: "人目も草も かれぬと思へば",
    romaji: "hitome mo kusa mo karenu to omoeba",
    meaning:
      "In the mountain village, winter is loneliest — visitors and grass alike wither.",
  },
  {
    id: "hi-29",
    number: 29,
    poet: "Ōshikōchi no Mitsune",
    reading: "心あてに 折らばや折らむ 初霜の 置きまどはせる 白菊の花",
    match: "置きまどはせる 白菊の花",
    romaji: "okimadowaseru shiragiku no hana",
    meaning: "Which white chrysanthemum is real, and which the first frost?",
  },
  {
    id: "hi-30",
    number: 30,
    poet: "Mibu no Tadamine",
    reading: "有明の つれなく見えし 別れより 暁ばかり 憂きものはなし",
    match: "暁ばかり 憂きものはなし",
    romaji: "akatsuki bakari uki mono wa nashi",
    meaning: "Since that cold parting, nothing is so bitter as the dawn.",
  },
  {
    id: "hi-31",
    number: 31,
    poet: "Sakanoue no Korenori",
    reading: "朝ぼらけ 有明の月と 見るまでに 吉野の里に 降れる白雪",
    match: "吉野の里に 降れる白雪",
    romaji: "Yoshino no sato ni fureru shirayuki",
    meaning: "White snow on Yoshino village, mistaken for the dawn moon.",
  },
  {
    id: "hi-32",
    number: 32,
    poet: "Harumichi no Tsuraki",
    reading: "山川に 風のかけたる しがらみは 流れもあへぬ 紅葉なりけり",
    match: "流れもあへぬ 紅葉なりけり",
    romaji: "nagare mo aenu momiji narikeri",
    meaning: "The weir across the stream is autumn leaves, too thick to flow.",
  },
  {
    id: "hi-33",
    number: 33,
    poet: "Ki no Tomonori",
    reading: "ひさかたの 光のどけき 春の日に しづ心なく 花の散るらむ",
    match: "しづ心なく 花の散るらむ",
    romaji: "shizu-gokoro naku hana no chiruramu",
    meaning:
      "Why do the blossoms scatter so restless in the calm spring light?",
  },
  {
    id: "hi-34",
    number: 34,
    poet: "Fujiwara no Okikaze",
    reading: "誰をかも 知る人にせむ 高砂の 松も昔の 友ならなくに",
    match: "松も昔の 友ならなくに",
    romaji: "matsu mo mukashi no tomo naranaku ni",
    meaning: "Whom can I call a friend? Even the pines are not friends of old.",
  },
  {
    id: "hi-35",
    number: 35,
    poet: "Ki no Tsurayuki",
    reading: "人はいさ 心も知らず ふるさとは 花ぞ昔の 香ににほひける",
    match: "花ぞ昔の 香ににほひける",
    romaji: "hana zo mukashi no ka ni nioikeru",
    meaning: "I know not your heart, but the blossoms still smell of old.",
  },
  {
    id: "hi-36",
    number: 36,
    poet: "Kiyowara no Fukayabu",
    reading: "夏の夜は まだ宵ながら 明けぬるを 雲のいづこに 月宿るらむ",
    match: "雲のいづこに 月宿るらむ",
    romaji: "kumo no izuko ni tsuki yadoruramu",
    meaning:
      "The summer night has dawned — where does the moon lodge in the clouds?",
  },
  {
    id: "hi-37",
    number: 37,
    poet: "Fun'ya no Asayasu",
    reading: "白露に 風の吹きしく 秋の野は つらぬきとめぬ 玉ぞ散りける",
    match: "つらぬきとめぬ 玉ぞ散りける",
    romaji: "tsuranuki tomenu tama zo chirikeru",
    meaning: "On the autumn field, dew-beads scatter like unstrung jewels.",
  },
  {
    id: "hi-38",
    number: 38,
    poet: "Ukon",
    reading: "忘らるる 身をば思はず 誓ひてし 人の命の 惜しくもあるかな",
    match: "人の命の 惜しくもあるかな",
    romaji: "hito no inochi no oshiku mo aru kana",
    meaning:
      "I do not mind being forgotten — but I dread the fate of the one who swore.",
  },
  {
    id: "hi-39",
    number: 39,
    poet: "Sangi Hitoshi",
    reading: "浅茅生の 小野の篠原 しのぶれど あまりてなどか 人の恋しき",
    match: "あまりてなどか 人の恋しき",
    romaji: "amarite nado ka hito no koishiki",
    meaning: "I hide it, yet why does my longing overflow?",
  },
  {
    id: "hi-40",
    number: 40,
    poet: "Taira no Kanemori",
    reading: "しのぶれど 色に出でにけり わが恋は ものや思ふと 人の問ふまで",
    match: "ものや思ふと 人の問ふまで",
    romaji: "mono ya omou to hito no tou made",
    meaning: "My love shows in my face, until people ask what troubles me.",
  },
  {
    id: "hi-41",
    number: 41,
    poet: "Mibu no Tadami",
    reading: "恋すてふ わが名はまだき 立ちにけり 人知れずこそ 思ひそめしか",
    match: "人知れずこそ 思ひそめしか",
    romaji: "hito shirezu koso omoi someshika",
    meaning: "Rumour of my love has spread, though I began it in secret.",
  },
  {
    id: "hi-42",
    number: 42,
    poet: "Kiyowara no Motosuke",
    reading: "契りきな かたみに袖を しぼりつつ 末の松山 波越さじとは",
    match: "末の松山 波越さじとは",
    romaji: "sue no Matsuyama nami kosaji to wa",
    meaning: "We vowed the waves would never cross Mount Sue.",
  },
  {
    id: "hi-43",
    number: 43,
    poet: "Fujiwara no Atsutada",
    reading: "逢ひ見ての のちの心に くらぶれば 昔は物を 思はざりけり",
    match: "昔は物を 思はざりけり",
    romaji: "mukashi wa mono o omowazarikeri",
    meaning: "Compared with love after meeting, my old longing was nothing.",
  },
  {
    id: "hi-44",
    number: 44,
    poet: "Fujiwara no Asatada",
    reading: "逢ふことの 絶えてしなくは なかなかに 人をも身をも 恨みざらまし",
    match: "人をも身をも 恨みざらまし",
    romaji: "hito o mo mi o mo uramizaramashi",
    meaning: "Had we never met, I would not resent you — or myself.",
  },
  {
    id: "hi-45",
    number: 45,
    poet: "Fujiwara no Koretada",
    reading: "あはれとも いふべき人は 思ほえで 身のいたづらに なりぬべきかな",
    match: "身のいたづらに なりぬべきかな",
    romaji: "mi no itazura ni narinubeki kana",
    meaning: "No one will pity me as I come to nothing.",
  },
  {
    id: "hi-46",
    number: 46,
    poet: "Sone no Yoshitada",
    reading: "由良のとを 渡る舟人 かぢを絶え ゆくへも知らぬ 恋の道かな",
    match: "ゆくへも知らぬ 恋の道かな",
    romaji: "yukue mo shiranu koi no michi kana",
    meaning:
      "Like a boatman who lost his oar — the road of love has no known end.",
  },
  {
    id: "hi-47",
    number: 47,
    poet: "Egyō Hōshi",
    reading: "八重葎 しげれる宿の さびしきに 人こそ見えね 秋は来にけり",
    match: "人こそ見えね 秋は来にけり",
    romaji: "hito koso miene aki wa kinikeri",
    meaning: "No visitor comes to the overgrown house, yet autumn has.",
  },
  {
    id: "hi-48",
    number: 48,
    poet: "Minamoto no Shigeyuki",
    reading: "風をいたみ 岩うつ波の おのれのみ くだけて物を 思ふころかな",
    match: "くだけて物を 思ふころかな",
    romaji: "kudakete mono o omou koro kana",
    meaning: "Like waves breaking on rock, I shatter alone in longing.",
  },
  {
    id: "hi-49",
    number: 49,
    poet: "Ōnakatomi no Yoshinobu",
    reading: "みかきもり 衛士のたく火の 夜は燃え 昼は消えつつ 物をこそ思へ",
    match: "昼は消えつつ 物をこそ思へ",
    romaji: "hiru wa kie tsutsu mono o koso omoe",
    meaning:
      "Like the guard's fire, I burn by night and fade by day in thought.",
  },
  {
    id: "hi-50",
    number: 50,
    poet: "Fujiwara no Yoshitaka",
    reading: "君がため 惜しからざりし 命さへ 長くもがなと 思ひけるかな",
    match: "長くもがなと 思ひけるかな",
    romaji: "nagaku mogana to omoikeru kana",
    meaning: "The life I would have spent for you — now I wish it long.",
  },
  {
    id: "hi-51",
    number: 51,
    poet: "Fujiwara no Sanekata",
    reading: "かくとだに えやはいぶきの さしも草 さしも知らじな 燃ゆる思ひを",
    match: "さしも知らじな 燃ゆる思ひを",
    romaji: "sashimo shiraji na moyuru omoi o",
    meaning: "She cannot know this burning longing, though I tell her so.",
  },
  {
    id: "hi-52",
    number: 52,
    poet: "Fujiwara no Michinobu",
    reading: "明けぬれば 暮るるものとは 知りながら なほ恨めしき 朝ぼらけかな",
    match: "なほ恨めしき 朝ぼらけかな",
    romaji: "nao urameshiki asaborake kana",
    meaning: "I know dawn must come, yet I resent the break of day.",
  },
  {
    id: "hi-53",
    number: 53,
    poet: "Udaishō Michitsuna no Haha",
    reading: "嘆きつつ ひとりぬる夜の 明くる間は いかに久しき ものとかは知る",
    match: "いかに久しき ものとかは知る",
    romaji: "ikani hisashiki mono to ka wa shiru",
    meaning: "Do you know how long a night alone with sighs can be?",
  },
  {
    id: "hi-54",
    number: 54,
    poet: "Takashina no Kishi",
    reading: "忘れじの ゆく末までは かたければ 今日を限りの 命ともがな",
    match: "今日を限りの 命ともがな",
    romaji: "kyō o kagiri no inochi to mo gana",
    meaning: "Since forever is hard to keep, let my life end today.",
  },
  {
    id: "hi-55",
    number: 55,
    poet: "Fujiwara no Kintō",
    reading: "滝の音は 絶えて久しく なりぬれど 名こそ流れて なほ聞こえけれ",
    match: "名こそ流れて なほ聞こえけれ",
    romaji: "na koso nagarete nao kikoekere",
    meaning:
      "The waterfall is silent now, yet its name still flows and is heard.",
  },
  {
    id: "hi-56",
    number: 56,
    poet: "Izumi Shikibu",
    reading: "あらざらむ この世のほかの 思ひ出に 今ひとたびの 逢ふこともがな",
    match: "今ひとたびの 逢ふこともがな",
    romaji: "ima hitotabi no au koto mo gana",
    meaning: "As a memory for the next world, let me meet you once more.",
  },
  {
    id: "hi-57",
    number: 57,
    poet: "Murasaki Shikibu",
    reading: "めぐり逢ひて 見しやそれとも わかぬ間に 雲がくれにし 夜半の月かな",
    match: "雲がくれにし 夜半の月かな",
    romaji: "kumo-gakure ni shi yowa no tsuki kana",
    meaning:
      "We met, and before I knew it you hid like the midnight moon in cloud.",
  },
  {
    id: "hi-58",
    number: 58,
    poet: "Daini no Sanmi",
    reading: "有馬山 猪名の笹原 風吹けば いでそよ人を 忘れやはする",
    match: "いでそよ人を 忘れやはする",
    romaji: "ide soyo hito o wasure ya wa suru",
    meaning: "When the wind stirs the bamboo, do you think I forget you?",
  },
  {
    id: "hi-59",
    number: 59,
    poet: "Akazome Emon",
    reading: "やすらはで 寝なましものを 小夜更けて かたぶくまでの 月を見しかな",
    match: "かたぶくまでの 月を見しかな",
    romaji: "katabuku made no tsuki o mishi kana",
    meaning: "I would have slept, but I watched the moon until it sank.",
  },
  {
    id: "hi-60",
    number: 60,
    poet: "Koshikibu no Naishi",
    reading: "大江山 いく野の道の 遠ければ まだふみも見ず 天の橋立",
    match: "まだふみも見ず 天の橋立",
    romaji: "mada fumi mo mizu ama no hashidate",
    meaning: "The road is long — I have not yet seen the bridge to heaven.",
  },
  {
    id: "hi-61",
    number: 61,
    poet: "Ise no Taifu",
    reading: "いにしへの 奈良の都の 八重桜 けふ九重に にほひぬるかな",
    match: "けふ九重に にほひぬるかな",
    romaji: "kyō kokonoe ni nioinuru kana",
    meaning:
      "The double blossoms of old Nara bloom today in the ninefold court.",
  },
  {
    id: "hi-62",
    number: 62,
    poet: "Sei Shōnagon",
    reading: "夜をこめて 鳥のそら音は はかるとも よに逢坂の 関はゆるさじ",
    match: "よに逢坂の 関はゆるさじ",
    romaji: "yo ni Ōsaka no seki wa yurusaji",
    meaning: "Though you crow like a false cock, the barrier will not open.",
  },
  {
    id: "hi-63",
    number: 63,
    poet: "Fujiwara no Michimasa",
    reading: "今はただ 思ひ絶えなむ とばかりを 人づてならで いふよしもがな",
    match: "人づてならで いふよしもがな",
    romaji: "hitozute narade iu yoshi mo gana",
    meaning: "If only I could tell you directly that I must give you up.",
  },
  {
    id: "hi-64",
    number: 64,
    poet: "Fujiwara no Sadayori",
    reading: "朝ぼらけ 宇治の川霧 たえだえに あらはれわたる 瀬々の網代木",
    match: "あらはれわたる 瀬々の網代木",
    romaji: "araware wataru seze no ajirogi",
    meaning: "Through the dawn mist on the Uji, the fishing weirs appear.",
  },
  {
    id: "hi-65",
    number: 65,
    poet: "Sagyō Hōshi",
    reading: "恨みわび ほさぬ袖だに あるものを 恋に朽ちなむ 名こそ惜しけれ",
    match: "恋に朽ちなむ 名こそ惜しけれ",
    romaji: "koi ni kuchinan na koso oshikere",
    meaning: "My sleeves may rot, but I dread a name ruined by love.",
  },
  {
    id: "hi-66",
    number: 66,
    poet: "Gyōson",
    reading: "もろともに あはれと思へ 山桜 花よりほかに 知る人もなし",
    match: "花よりほかに 知る人もなし",
    romaji: "hana yori hoka ni shiru hito mo nashi",
    meaning: "Mountain cherry, pity me — I have no friend but the blossoms.",
  },
  {
    id: "hi-67",
    number: 67,
    poet: "Suō no Naishi",
    reading: "春の夜の 夢ばかりなる 手枕に かひなく立たむ 名こそ惜しけれ",
    match: "かひなく立たむ 名こそ惜しけれ",
    romaji: "kainaku tatan na koso oshikere",
    meaning: "For a pillow of a spring-night dream, I would not risk my name.",
  },
  {
    id: "hi-68",
    number: 68,
    poet: "Emperor Sanjō",
    reading: "心にも あらでうき世に ながらへば 恋しかるべき 夜半の月かな",
    match: "恋しかるべき 夜半の月かな",
    romaji: "koishikarubeki yowa no tsuki kana",
    meaning:
      "If I live on against my will, I will long for this midnight moon.",
  },
  {
    id: "hi-69",
    number: 69,
    poet: "Nōin Hōshi",
    reading: "嵐吹く 三室の山の もみぢ葉は 龍田の川の 錦なりけり",
    match: "龍田の川の 錦なりけり",
    romaji: "Tatsuta no kawa no nishiki narikeri",
    meaning:
      "The storm-blown leaves of Mimuro are brocade on the Tatsuta river.",
  },
  {
    id: "hi-70",
    number: 70,
    poet: "Ryōzen Hōshi",
    reading: "さびしさに 宿を立ち出でて ながむれば いづこも同じ 秋の夕暮れ",
    match: "いづこも同じ 秋の夕暮れ",
    romaji: "izuko mo onaji aki no yūgure",
    meaning:
      "I leave my hut in loneliness — everywhere it is the same autumn dusk.",
  },
  {
    id: "hi-71",
    number: 71,
    poet: "Minamoto no Tsunenobu",
    reading: "夕されば 門田の稲葉 おとづれて 芦のまろやに 秋風ぞ吹く",
    match: "芦のまろやに 秋風ぞ吹く",
    romaji: "ashi no maroya ni akikaze zo fuku",
    meaning: "At evening the autumn wind blows through the reed-thatched hut.",
  },
  {
    id: "hi-72",
    number: 72,
    poet: "Kii no Tomonori",
    reading: "音に聞く 高師の浜の あだ波は かけじや袖の ぬれもこそすれ",
    match: "かけじや袖の ぬれもこそすれ",
    romaji: "kakeji ya sode no nure mo koso sure",
    meaning: "I will not trust the fickle waves — my sleeves would only wet.",
  },
  {
    id: "hi-73",
    number: 73,
    poet: "Ōe no Masafusa",
    reading: "高砂の 尾の上の桜 咲きにけり 外山の霞 立たずもあらなむ",
    match: "外山の霞 立たずもあらなむ",
    romaji: "toyama no kasumi tatazu mo aranan",
    meaning:
      "The cherry on the peak has bloomed — let no mist rise on the outer hills.",
  },
  {
    id: "hi-74",
    number: 74,
    poet: "Minamoto no Toshiyori",
    reading: "うかりける 人を初瀬の 山おろしよ はげしかれとは 祈らぬものを",
    match: "はげしかれとは 祈らぬものを",
    romaji: "hageshikare to wa inoranu mono o",
    meaning:
      "I never prayed the wind would blow so hard against the one I love.",
  },
  {
    id: "hi-75",
    number: 75,
    poet: "Fujiwara no Mototoshi",
    reading: "契りおきし させもが露を 命にて あはれ今年の 秋もいぬめり",
    match: "あはれ今年の 秋もいぬめり",
    romaji: "aware kotoshi no aki mo inumeri",
    meaning: "Trusting in promised dew, alas, this autumn too has passed.",
  },
  {
    id: "hi-76",
    number: 76,
    poet: "Fujiwara no Tadamichi",
    reading: "わたの原 漕ぎ出でて見れば ひさかたの 雲居にまがふ 沖つ白波",
    match: "雲居にまがふ 沖つ白波",
    romaji: "kumoi ni magau oki tsu shiranami",
    meaning: "Rowing out, the white waves offshore look like clouds.",
  },
  {
    id: "hi-77",
    number: 77,
    poet: "Emperor Sutoku",
    reading: "瀬をはやみ 岩にせかるる 滝川の われても末に 逢はむとぞ思ふ",
    match: "われても末に 逢はむとぞ思ふ",
    romaji: "warete mo sue ni awan to zo omou",
    meaning:
      "Though parted like a stream split by rock, I will meet you at the end.",
  },
  {
    id: "hi-78",
    number: 78,
    poet: "Minamoto no Kanemasa",
    reading: "淡路島 通ふ千鳥の 鳴く声に 幾夜寝覚めぬ 須磨の関守",
    match: "幾夜寝覚めぬ 須磨の関守",
    romaji: "ikuyo nezamenu Suma no sekimori",
    meaning: "How many nights has the Suma guard woken to the plovers' cry?",
  },
  {
    id: "hi-79",
    number: 79,
    poet: "Fujiwara no Akisuke",
    reading: "秋風に たなびく雲の 絶え間より もれ出づる月の 影のさやけさ",
    match: "もれ出づる月の 影のさやけさ",
    romaji: "moredzuru tsuki no kage no sayakesa",
    meaning:
      "Through a break in the wind-tossed clouds, the moon's clear light.",
  },
  {
    id: "hi-80",
    number: 80,
    poet: "Taikenmon'in no Horikawa",
    reading: "長からむ 心も知らず 黒髪の 乱れて今朝は 物をこそ思へ",
    match: "乱れて今朝は 物をこそ思へ",
    romaji: "midarete kesa wa mono o koso omoe",
    meaning:
      "Not knowing your heart, my black hair tangled, I brood this morning.",
  },
  {
    id: "hi-81",
    number: 81,
    poet: "Fujiwara no Sanesada",
    reading: "ほととぎす 鳴きつる方を ながむれば ただ有明の 月ぞ残れる",
    match: "ただ有明の 月ぞ残れる",
    romaji: "tada ariake no tsuki zo nokoreru",
    meaning: "I looked where the cuckoo called — only the dawn moon remained.",
  },
  {
    id: "hi-82",
    number: 82,
    poet: "Dōin Hōshi",
    reading: "思ひわび さても命は あるものを 憂きにたへぬは 涙なりけり",
    match: "憂きにたへぬは 涙なりけり",
    romaji: "uki ni taenu wa namida narikeri",
    meaning: "I live on in sorrow, but what cannot bear it is my tears.",
  },
  {
    id: "hi-83",
    number: 83,
    poet: "Fujiwara no Toshinari",
    reading: "世の中よ 道こそなけれ 思ひ入る 山の奥にも 鹿ぞ鳴くなる",
    match: "山の奥にも 鹿ぞ鳴くなる",
    romaji: "yama no oku ni mo shika zo naku naru",
    meaning:
      "There is no escape from the world — even deep in the hills, a deer calls.",
  },
  {
    id: "hi-84",
    number: 84,
    poet: "Fujiwara no Kiyosuke",
    reading: "ながらへば またこのごろや しのばれむ 憂しと見し世ぞ 今は恋しき",
    match: "憂しと見し世ぞ 今は恋しき",
    romaji: "ushi to mishi yo zo ima wa koishiki",
    meaning: "If I live on, I will long for the very days I thought bitter.",
  },
  {
    id: "hi-85",
    number: 85,
    poet: "Shun'e Hōshi",
    reading: "夜もすがら 物思ふころは 明けやらで 閨のひまさへ つれなかりけり",
    match: "閨のひまさへ つれなかりけり",
    romaji: "neya no hima sae tsurenakarikeri",
    meaning: "All night in thought, even the gap in my door seems cold.",
  },
  {
    id: "hi-86",
    number: 86,
    poet: "Saigyō Hōshi",
    reading: "嘆けとて 月やは物を 思はする かこち顔なる わが涙かな",
    match: "かこち顔なる わが涙かな",
    romaji: "kakochigao naru waga namida kana",
    meaning: "Does the moon make me sigh? These tears only blame it.",
  },
  {
    id: "hi-87",
    number: 87,
    poet: "Jakuren Hōshi",
    reading: "村雨の 露もまだひぬ まきの葉に 霧立ちのぼる 秋の夕暮れ",
    match: "霧立ちのぼる 秋の夕暮れ",
    romaji: "kiri tachinoboru aki no yūgure",
    meaning:
      "On the cedar leaves still wet with rain, mist rises at autumn dusk.",
  },
  {
    id: "hi-88",
    number: 88,
    poet: "Kakimon'in no Betō",
    reading: "難波江の 芦のかりねの ひと夜ゆゑ みをつくしてや 恋ひわたるべき",
    match: "みをつくしてや 恋ひわたるべき",
    romaji: "mi o tsukushite ya koiwatarubeki",
    meaning: "For one short night, must I love away my whole life?",
  },
  {
    id: "hi-89",
    number: 89,
    poet: "Princess Shikishi",
    reading: "玉の緒よ 絶えなば絶えね ながらへば 忍ぶることの 弱りもぞする",
    match: "忍ぶることの 弱りもぞする",
    romaji: "shinoburu koto no yowari mo zo suru",
    meaning: "Thread of life, break if you must — endurance is failing me.",
  },
  {
    id: "hi-90",
    number: 90,
    poet: "Inpumon'in no Taifu",
    reading: "見せばやな 雄島のあまの 袖だにも 濡れにぞ濡れし 色は変はらず",
    match: "濡れにぞ濡れし 色は変はらず",
    romaji: "nure ni zo nureshi iro wa kawarazu",
    meaning:
      "Even the fisher's soaked sleeve keeps its colour — would that I could show it.",
  },
  {
    id: "hi-91",
    number: 91,
    poet: "Fujiwara no Yoshitsune",
    reading: "きりぎりす 鳴くや霜夜の さむしろに 衣かたしき ひとりかも寝む",
    match: "衣かたしき ひとりかも寝む",
    romaji: "koromo katashiki hitori kamo nemu",
    meaning:
      "On a frosty night of cricket song, I spread half my robe and sleep alone.",
  },
  {
    id: "hi-92",
    number: 92,
    poet: "Nijōin no Sanuki",
    reading: "わが袖は 潮干に見えぬ 沖の石の 人こそ知らね 乾く間もなし",
    match: "人こそ知らね 乾く間もなし",
    romaji: "hito koso shirane kawaku ma mo nashi",
    meaning:
      "My sleeves are like a rock hidden at low tide — never dry, though none know.",
  },
  {
    id: "hi-93",
    number: 93,
    poet: "Minamoto no Sanetomo",
    reading: "世の中は 常にもがもな 渚漕ぐ あまの小舟の 綱手かなしも",
    match: "あまの小舟の 綱手かなしも",
    romaji: "ama no obune no tsunade kanashi mo",
    meaning:
      "Would the world were unchanging — how dear the rope-pullers of the fishing boats.",
  },
  {
    id: "hi-94",
    number: 94,
    poet: "Fujiwara no Masatsune",
    reading: "み吉野の 山の秋風 さ夜更けて ふるさと寒く 衣打つなり",
    match: "ふるさと寒く 衣打つなり",
    romaji: "furusato samuku koromo utsu nari",
    meaning:
      "In Yoshino the night deepens, and the old village beats cloth in the cold.",
  },
  {
    id: "hi-95",
    number: 95,
    poet: "Jien",
    reading: "おほけなく 憂き世の民に おほふかな わが立つ杣に 墨染の袖",
    match: "わが立つ杣に 墨染の袖",
    romaji: "waga tatsu soma ni sumizome no sode",
    meaning: "Boldly I spread my ink-dyed sleeve over the sorrowing world.",
  },
  {
    id: "hi-96",
    number: 96,
    poet: "Fujiwara no Kintsune",
    reading: "花さそふ 嵐の庭の 雪ならで ふりゆくものは わが身なりけり",
    match: "ふりゆくものは わが身なりけり",
    romaji: "furiyuku mono wa waga mi narikeri",
    meaning: "Not the snow of the storm-swept garden — it is I who grow old.",
  },
  {
    id: "hi-97",
    number: 97,
    poet: "Fujiwara no Teika",
    reading: "こぬ人を まつほの浦の 夕なぎに 焼くや藻塩の 身もこがれつつ",
    match: "焼くや藻塩の 身もこがれつつ",
    romaji: "yaku ya moshio no mi mo kogaretsutsu",
    meaning:
      "Like seaweed burned for salt at Matsuho bay, I burn for the one who does not come.",
  },
  {
    id: "hi-98",
    number: 98,
    poet: "Fujiwara no Ietaka",
    reading: "風そよぐ ならの小川の 夕暮れは みそぎぞ夏の しるしなりける",
    match: "みそぎぞ夏の しるしなりける",
    romaji: "misogi zo natsu no shirushi narikeru",
    meaning:
      "In the evening breeze on the Nara stream, the purification rite marks summer's end.",
  },
  {
    id: "hi-99",
    number: 99,
    poet: "Emperor Go-Toba",
    reading: "人もをし 人もうらめし あぢきなく 世を思ふゆゑに 物思ふ身は",
    match: "世を思ふゆゑに 物思ふ身は",
    romaji: "yo o omou yue ni mono omou mi wa",
    meaning:
      "People are dear, people are hateful — because I think of the world, I brood.",
  },
  {
    id: "hi-100",
    number: 100,
    poet: "Emperor Juntoku",
    reading: "ももしきや 古き軒端の しのぶにも なほあまりある 昔なりけり",
    match: "なほあまりある 昔なりけり",
    romaji: "nao amari aru mukashi narikeri",
    meaning: "Even the moss on the old palace eaves cannot hold all the past.",
  },
];

/** Number of cards dealt into a single practice round. */
export const ROUND_SIZE = 6;

/** Fisher–Yates shuffle returning a new array. */
export function shuffle<T>(items: readonly T[]): T[] {
  const copy = [...items];
  for (let i = copy.length - 1; i > 0; i -= 1) {
    const j = Math.floor(Math.random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy;
}

/**
 * Build one round: a reading card plus `ROUND_SIZE - 1` decoy match cards,
 * all shuffled together. The reading card is always included.
 */
export function buildRound(
  deck: readonly KarutaCard[],
  size: number = ROUND_SIZE,
): { reading: KarutaCard; choices: KarutaCard[] } {
  const reading = deck[Math.floor(Math.random() * deck.length)];
  const decoys = shuffle(deck.filter((card) => card.id !== reading.id)).slice(
    0,
    Math.max(0, size - 1),
  );
  return { reading, choices: shuffle([reading, ...decoys]) };
}
