/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cell { 'value' : Value, 'name' : string }
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface NoteView {
  'id' : bigint,
  'title' : string,
  'body' : string,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'pinned' : boolean,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createNote' : ActorMethod<[string, string], NoteView>,
  'deleteNote' : ActorMethod<[bigint], boolean>,
  'execute' : ActorMethod<[string], Result>,
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChineseLearned' : ActorMethod<[], Array<string>>,
  'getChineseProgress' : ActorMethod<[], bigint>,
  'getJapaneseLearned' : ActorMethod<[string], Array<string>>,
  'getJapaneseProgress' : ActorMethod<[string], bigint>,
  'getNote' : ActorMethod<[bigint], [] | [NoteView]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listNotes' : ActorMethod<[[] | [string]], Array<NoteView>>,
  'markChineseLearned' : ActorMethod<[string, boolean], undefined>,
  'markJapaneseLearned' : ActorMethod<[string, string, boolean], undefined>,
  'schema' : ActorMethod<[], string>,
  'setNotePinned' : ActorMethod<[bigint, boolean], [] | [NoteView]>,
  'updateNote' : ActorMethod<[bigint, string, string], [] | [NoteView]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];